apiVersion: v1
kind: Secret
metadata:
  name: dbts
type: Opaque
data:
  DISCORD_TOKEN: <base64_your_discord_bot_token>
  DISCORD_GUILD: <base64_your_discord_guild_name>
  DISCORD_CHANNEL_ID: <base64_your_discord_channel_id>
  SYMBOL: U09MVVNEVA==
  INTERVAL: MQ==
  RSI_PERIOD: MTQ=
